name: Coverage

# This workflow generates a coverage report (how much of the codebase is covered by the
# unit tests) and uploads the information to Coveralls.io for reporting and analysis.

on:
  push:  # TURN OFF
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install UrbanSim Templates
      run: |
        pip install .
        pip install -r requirements-extras.txt
        pip install -r requirements-dev.txt
    - name: Run tests
      run: |
        cd tests
        coverage run --source urbansim_templates --module pytest --verbose
    - name: Upload to Coveralls
      run: |
        coveralls
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
