name: Cross-compatibility

# This workflow runs the UrbanSim Templates unit tests across a comprehensive range of
# Python versions and operating systems.

on:
  push:  # TURN OFF
  pull_request:
  workflow_dispatch:

jobs:
  build-pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]  # no pip pytables for py39-mac or py39-win
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install UrbanSim Templates
      run: |
        pip install .
        pip install -r requirements-extras.txt
        pip install -r requirements-dev.txt
    - name: Run tests
      run: |
        cd tests
        py.test *.py -s
